/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface HeatPump {
  brandName: string;
  modelNumber: string;
  modelType: string;
  weightInKg: number;
  widthInCm: number;
  heighInCm: number;
  DepthInCm: number;
  TankCapacity: number;
  indoorOutDoor: "indoor" | "outdoor";
  amperage: number;
  voltage: number;
  powerConsumption: number;
  electricalPhase: 1 | 3;
  circuitRequired: boolean;
  circuitCapacity: number;
  performanceRating: string;
  soundLevel?: number;
  taxRebate?: boolean;
}
